---
title: "Quellen"
---

## Geprüfte Startquellen

- Robert Koch-Institut (2025): [Die Lebenserwartungslücke: Sozioökonomische Unterschiede in der Lebenserwartung zwischen Deutschlands Regionen](https://www.rki.de/DE/Aktuelles/Publikationen/Journal-of-Health-Monitoring/GBEDownloadsJ/Focus/JHealthMonit_2025_01_Lebenserwartungsluecke.html).
- Bundesministerium für Wirtschaft und Klimaschutz / BMI (2024): [Gleichwertigkeitsbericht 2024](https://www.bundeswirtschaftsministerium.de/Redaktion/DE/Pressemitteilungen/2024/07/20240703-gleichwertigkeitsbericht.html).
- Friedrich-Ebert-Stiftung (2025): [Mitte-Studie 2024/25 - Die angespannte Mitte](https://www.fes.de/mitte-studie/news-seite).
- Bertelsmann Stiftung (2025): [Spotlight Gesundheit 01/2025 - Hausärztliche Versorgung der Zukunft](https://www.bertelsmann-stiftung.de/de/spotlight-gesundheit-01/2024-1-1-1).
- OECD (2024): [Trust in day-to-day interactions with public institutions](https://www.oecd.org/en/publications/2024/07/oecd-survey-on-drivers-of-trust-in-public-institutions-2024-results_eeb36452/full-report/trust-in-day-to-day-interactions-with-public-institutions_7d0e07b0.html).
- Robert Bosch Stiftung / Bosch Health Campus: [PORT - Patientenorientierte Zentren zur Primär- und Langzeitversorgung](https://www.bosch-stiftung.de/de/projekt/port-patientenorientierte-zentren-zur-primaer-und-langzeitversorgung/im-detail).
- Neue Gesundheitsnetze: [Gesundheitszentrum Büsum](https://www.neue-gesundheitsnetze.de/praxisbeispiele/buesum/).
- G-BA Innovationsfonds: [IGiB-StimMT - Strukturmigration im Mittelbereich Templin](https://innovationsfonds.g-ba.de/projekte/neue-versorgungsformen/igib-stimmt.79).
- Universität Siegen: [INVEST II - Evaluation des Gesundheitskiosks Billstedt/Horn](https://www.uni-siegen.de/projekt/invest-ii-evaluation-des-integrierten-versorgungsmodells-in-billstedt/horn-gesundheitskiosk).
- PubMed / Deutsches Ärzteblatt International: [Ten-Year Evaluation of Gesundes Kinzigtal](https://pubmed.ncbi.nlm.nih.gov/33867008/).
- Gov.ie: [Slaintecare Healthy Communities](https://www.gov.ie/en/healthy-ireland/publications/sl%C3%A1intecare-healthy-communities/).
- NHS England: [Social prescribing](https://www.england.nhs.uk/personalisedcare/social-prescribing/).
- Neue Gesundheitsnetze: [Beispiele im Überblick](https://www.neue-gesundheitsnetze.de/praxisbeispiele/).
- Neue Gesundheitsnetze: [HaffNet am Stettiner Haff](https://www.neue-gesundheitsnetze.de/praxisbeispiele/haffnet/).
- Neue Gesundheitsnetze: [Ärztenetz Eutin-Malente](https://www.neue-gesundheitsnetze.de/praxisbeispiele/eutin-malente/).
- Neue Gesundheitsnetze: [ParkinsonNetzwerk Ostsachsen](https://www.neue-gesundheitsnetze.de/praxisbeispiele/panos/).
- Neue Gesundheitsnetze: [Unternehmung Gesundheit Hochfranken](https://www.neue-gesundheitsnetze.de/praxisbeispiele/ugho/).
- Neue Gesundheitsnetze: [prosper proGesund Modell der KNAPPSCHAFT](https://www.neue-gesundheitsnetze.de/praxisbeispiele/prosper/).
- Gesundheitskollektiv Berlin: [GeKo Stadtteil-Gesundheits-Zentrum Neukölln](https://geko-berlin.de/).
- Poliklinik Veddel: [Stadtteil-Gesundheitszentrum](https://poliklinik1.org/).
- G-BA Innovationsfonds: [StatAMed](https://innovationsfonds.g-ba.de/projekte/neue-versorgungsformen/statamed.563).
- G-BA Innovationsfonds: [NAVIGATION](https://innovationsfonds.g-ba.de/projekte/navigation.635).
- G-BA Innovationsfonds: [HI-PLUS](https://innovationsfonds.g-ba.de/projekte/hi-plus.378).
- Robert Bosch Stiftung: [Centros de Salud in Spanien](https://www.bosch-stiftung.de/de/publikation/port-patientenorientierte-zentren-zur-primaer-und-langzeitversorgung-gesundheitszentren).
- Robert Bosch Stiftung: [Vardcentraler in Nordschweden](https://www.bosch-stiftung.de/de/publikation/port-patientenorientierte-zentren-zur-primaer-und-langzeitversorgung-versorgungszentren).
- Robert Bosch Stiftung: [Zdravstveni Domovi in Slowenien](https://www.bosch-stiftung.de/de/publikation/port-patientenorientierte-zentren-zur-primaer-und-langzeitversorgung-0).
- Suomi.fi: [Wellbeing Services Counties](https://www.suomi.fi/citizen/rights-and-participation-in-society/legal-and-consumer-protection/guide/how-finlands-public-administration-works/wellbeing-services-county).
- Bosch Health Campus: [PORT-Standorte](https://www.bosch-health-campus.de/de/projekt/port-patientenorientierte-zentren-zur-primaer-und-langzeitversorgung/standorte).
- Stadt Essen: [Gesundheit im Essener Norden - Gesundheitskioske](https://www.essen.de/leben/gesundheit/gesundheit_im_essener_norden/gesundheit_im_essener_norden_gesundheitskioske.de.html).
- G-BA Innovationsfonds: [ILEG - Gemeindenotfallsanitäter](https://innovationsfonds.g-ba.de/projekte/ileg.308).
- Deutsches Ärzteblatt: [Telemedizinische Unterstützung von Hausbesuchen](https://www.aerzteblatt.de/news/telemedizinische-unterstuetzung-von-hausbesuchen-startet-in-vier-bundeslaendern-51a2006d-15cd-4bbe-af15-5f0f8ec231de).
- G-BA Innovationsfonds: [Telnet@NRW](https://innovationsfonds.g-ba.de/projekte/telnetatnrw.84).
- Robert Bosch Stiftung: [Community Health Nursing](https://www.bosch-stiftung.de/de/projekt/community-health-nursing).
- Österreichisches Gesundheitsportal: [Primärversorgungseinheiten](https://www.gesundheit.gv.at/gesundheitsleistungen/primaerversorgung/primaerversorgungseinheiten.html).
- Buurtzorg: [About Buurtzorg](https://www.buurtzorg.com/about-us/).
- Ministère de la Santé: [Plan für Maisons de santé pluriprofessionnelles](https://sante.gouv.fr/actualites/presse/communiques-de-presse/article/acces-aux-soins-dans-les-territoires-agnes-firmin-le-bodo-a-annonce-le-plan-d).

## Quellenarbeit

Jede Quelle erhält im Rechercheprozess einen Status:

- `gefunden`
- `geprüft`
- `zitiert`
- `archiviert`

Nur geprüfte und zitierfähige Quellen werden in finalen Publikationen verwendet. Für Fallstudien werden zusätzlich lokale Dokumente, Evaluationsberichte und Interviews herangezogen.



